#version: '3.8'
services:
  # Service aplikasi Node.js kamu
  webhook-app:
    build: .
    container_name: my_webhook_container
    ports:
      - '3000:3000'
      # --- TAMBAHKAN BAGIAN INI ---
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: nodemon --poll app.js
    # ----------------------------
    environment:
      # Mengambil dari .env
      - VERIFY_TOKEN=${MY_WEBHOOK_VERIFY_TOKEN}
      - PORT=3000
    restart: always

  # Service Ngrok (Otomatis tunneling)
  ngrok:
    image: ngrok/ngrok:latest
    restart: always
    command:
      - 'http'
      - 'webhook-app:3000'
    environment:
      # Mengambil dari .env
      - NGROK_AUTHTOKEN=${MY_NGROK_TOKEN}
    ports:
      - '4040:4040'
    depends_on:
      - webhook-app
